server:
  port: 8001
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa: 
    open-in-view: true
    hibernate:
      ddl-auto: creat #creat :실행할때마다 테이블을 새로만든다
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Entity(테이블) 이름그대로 필드를 만들어준다 
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
